### ISSUE TITLE
The opensarlab_lib has no get_max/min _extents

### ISSUE THREAD

**Issue by yakunhan** [ASFHyP3/ASFHyP3.github.io#6]
When I Preparing a HyP3 InSAR Stack for MintPy，when I run  the Determine the maximum and common extents of the stack and plot an Area-of_Interest Selector: amp = list(analysis_directory.glob(f'*/*_amp*.tif'))
max_extents = asfn.get_max_extents(amp) 

The results show module ' opensarlab_lib' has no attribute 'get_max_extents' and I also couldn't serach the get_max_extents in the opensarlab_lib, could you have solutions for this issue.

**Comment by asjohnston-asf** [comment]
I see the same after installing opensarlab_lib v0.0.8:
```
>>> import opensarlab_lib as asfn
>>> asfn.__version__
'0.0.8'
>>> asfn.get_
asfn.get_RTC_polarizations(   asfn.get_job_dates(           asfn.get_power_set(           asfn.get_slider_vals(
asfn.get_corner_coords(       asfn.get_polarity_from_path(  asfn.get_projection( 
```

I assume you're attempting to run Step #3 of the notebook at https://github.com/ASFOpenSARlab/opensarlab-notebooks/blob/master/SAR_Training/English/Master/Prepare_HyP3_InSAR_Stack_for_MintPy.ipynb ?

@dgpalmieri @Alex-Lewandowski @ruikawahara @emlundell can one of you provide guidance? Should we expect to be able to complete that notebook successfully?

**Comment by Alex-Lewandowski** [comment]
It looks like we dropped the ball on this one. We updated a couple notebooks with changes that require an update to opensarlab-lib which hasn't yet been released on PyPi and conda-forge. We will tackle this today and respond here when it is ready.

**Comment by Alex-Lewandowski** [comment]
opensarlab_lib 0.0.9 is live on conda-forge. Please recreate your `insar_analysis` environment using ~/conda_environments/Create_OSL_Conda_Environments.ipynb and try rerunning the MintPy notebooks.

**Comment by jhkennedy** [comment]
Closing as solved -- @yakunhan please re-open if you're still seeing errors.
